server {
  listen 0.0.0.0:8080;
  root /tmp/www;
  index index.html;

  error_page 404 /errors/404.txt;

  location /upload {
    allow_methods POST;
    upload_dir /tmp/uploads;
  }

  location / {
    allow_methods GET;
    autoindex on;
  }
}
