server {
  listen 127.0.0.1:8080;
  root ./www;
  index index.html;

  location /images/ {
    autoindex on;
  }

  location /old/ {
    return 301 /new/;
  }

  location /admin/ {
    allow_methods GET;
  }
}
