name: Webserv CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # Устанавливаем компилятор
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential valgrind

      # Сборка проекта
      - name: Build
        run: |
          make debug

      # Проверка запуска
      - name: Run server (smoke test)
        run: |
          ./webserv config/default.conf &
          sleep 2
          curl http://localhost:8080 || exit 1

      # Проверка на утечки
      - name: Valgrind check
        run: |
          valgrind --leak-check=full ./webserv config/default.conf &
          sleep 2

      # Тесты
      - name: HTTP tests
        run: |
          ./webserv config/default.conf &
          sleep 2

          # Проверка 200 OK
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 | grep 200

          # Проверка 404
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/notfound | grep 404
